CREATE TABLE employees	(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	firstName VARCHAR (100) NOT NULL,
	lastName VARCHAR (100) NOT NULL,
	email VARCHAR (100) NOT NULL UNIQUE,
	phone VARCHAR (20) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);